name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Добавляем установку TypeScript и ts-node
      - name: Install TypeScript dependencies
        run: npm install -D typescript ts-node @types/node webpack webpack-cli

      # Проверяем структуру файлов (для отладки)
      - name: Check project structure
        run: ls -R config/

      # Сначала запускаем линтинг
      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting SCSS
        run: npm run lint:scss

      # Затем тесты
      - name: Unit testing
        run: npm run test:unit

      # И только потом сборку
      - name: Build production project
        run: npm run build:prod
